version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
  test:
    steps:
      - checkout
      - run:
          name: Print node version
          command: node --version
      - run:
          name: Install dev dependencies
          command: npm install --save-dev
      - run:
          name: Accessibility check
          command: npm run pa11y
